### ISSUE TITLE
Better navigation between pages

### ISSUE THREAD

**Issue by LivingWithHippos** [LivingWithHippos/unchained-android#392]
Right now we have a multiple navigation backstack and it's not possible to easily jump between fragment in these, we use a trick to click on the bottom bar and notify the activity to open the correct fragment

Using a single navigation stack we can use global destination and open pages from wherever, which makes sending stuff or opening links in Unchained much easier.

## todo

- [ ] use a single navigation stack
- [ ] bottom bar must work correctly
- [ ] pressing back must work correctly (some issues right now, maybe also update it to avoid the deprecation notice?)
- [ ] shared links must be opened correctly (multiple links included)
- [ ] shared torrents/containers must work correctly
- [ ] shared magnet must work correctly
- [ ] may as well implement #302  at this point
